### ISSUE TITLE
Getting this error - Unrecognised Secrets

### ISSUE THREAD

**Issue by ucalyptus** [GokulDas027/TelegramBridge#2]
##[error](Line: 7, Col: 14): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.chat
##[error](Line: 10, Col: 14): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.token
##[error]Fail to load /home/runner/work/_actions/GokulDas027/TelegramBridge/master/action.yml

**Comment by ucalyptus** [comment]
check this https://github.com/ucalyptus/Pneumothorax-Segmentation-using-Hypercolumns/blob/master/.github/workflows/main.yml

**Comment by GokulDas027** [comment]
Yeah, 
You've to save your credentials, like 
the Bot's token and The chat id in the repo secrets, with name 'token' and 'chat' respectively.

**Comment by GokulDas027** [comment]
Sorry, It was an error on my final commit 😅.
It was a change in action.yml intended to make the plugin usage more easier. Unfortunately it did happened as expected.
It's fixed now. Please check and feedback.
