### ISSUE TITLE
Unable to send message: unescaped dash

### ISSUE THREAD

**Issue by ashpool37** [GokulDas027/TelegramBridge#3]
I'm getting this error message when running Notifier:
`unable to send message: Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'`
I suspect this is due to our organization name containing dashes. Please make sure dash symbols in organization and repository names are escaped.

**Comment by GokulDas027** [comment]
fixed in the newest release (1.0.c)
please check and feedback if anything persists 🙂
Happy to know this tool is helping you.
Not much testing was done before, was in a "personal project" privilege 😄
